name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deploy # Tu rama de trabajo

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Dónde está tu código
          output_location: "" # Azure detecta automáticamente .next para Next.js
        env:
          # ESTO ES VITAL: Inyectamos la URL del backend desplegado
          NEXT_PUBLIC_API_URL: "https://app-adopcion-backend-dev.azurewebsites.net/api"
          NEXT_PUBLIC_APP_URL: "https://tu-url-de-frontend.azurestaticapps.net"
